pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:
  only:
  - master

image: Visual Studio 2019

init:
- ps: >-
    $env:ABBREV_COMMIT = $env:APPVEYOR_REPO_COMMIT.substring(0,8)

configuration: Debug
version: '0.2.{build}.0'
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(ABBREV_COMMIT)"

before_build:
  - cmd: >-
      dotnet tool install -g dotnet-format --version 5.0.142902 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

  - cmd: >-
      dotnet-format --check

  - cmd: >-
      nuget restore

after_build:
  - cmd: >-
      "%USERPROFILE%"\.nuget\packages\ILRepack\2.0.17\tools\ILRepack.exe /out:build/Chemo.exe src\Chemo\bin\Debug\Chemo.exe src\Chemo\bin\Debug\Microsoft.Dism.dll

      cp build\Chemo.exe Chemo.exe

artifacts:
  - path: build
    name: Dev_Resources

  - path: Chemo.exe
    name: Chemo.exe
