pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:
  only:
  - master

image: Visual Studio 2017

init:
- ps: >-
    $env:ABBREV_COMMIT = $env:APPVEYOR_REPO_COMMIT.substring(0,8)

configuration: Release
version: '0.2.{build}.0'
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(ABBREV_COMMIT)"

build_script:
  - nuget restore
  - msbuild /BinaryLogger /Logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - %USERPROFILE%\.nuget\packages\ILRepack\2.0.17\tools\ILRepack.exe /out:build/Chemo.exe Chemo\bin\Release\Chemo.exe Chemo\bin\Release\Microsoft.Dism.dll
  - cp build\Chemo.exe Chemo.exe

artifacts:
  - path: build
    name: Dev_Resources

  - path: Chemo.exe
    name: Chemo.exe
